### ISSUE TITLE
Set up deployment

### ISSUE THREAD

**Issue by HomoCodens** [swissjobtracker/swissjobtracker.github.io#1]
- [ ] protec main branch
- [ ] set up GH-actions to build and deploy
- [ ] research option to deploy dev version(s)

**Comment by HomoCodens** [comment]
I think if we're hosting on github, deploying multiple versions (e.g. dev & prod) won't work. Unless we have them in different subdirectories.

**Comment by mbannert** [comment]
resolved in different fashion: 

- run `npm run deploy` locally, will build locally and push content of dist/spa to gh-pages root dir
- we use the push dir ext as suggested by quasar: https://quasar.dev/quasar-cli-webpack/developing-spa/deploying
- this is in line with the local build approach of the quarto based blog. 
- feel free to add  a GH actions based procedure
- online dev version would run in separate repository, adapt package.json scripts and add a `devdeploy` script that pushes to a different repository that just contains the artifacts of the built process, use GH Pages again to display website at a different URL.
